version: '3'
services:
  # autoheal:
  #   restart: always
  #   image: willfarrell/autoheal
  #   environment:
  #     - AUTOHEAL_CONTAINER_LABEL=all
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  regular_node:
    env_file: .language_server.env
    build: .

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm build && pnpm start:regular"
    ports:
      - '12390:12390'
    volumes:
      - ./downloads:/telestory-ts-backend/downloads
    restart: unless-stopped
